[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "mail-sender"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
    "python-dotenv",
    "PySide6",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-mock",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["email_tool*"]

[tool.pytest.ini_options]
testpaths = ["tests"]